### ISSUE TITLE
Floor and ceiling swapped in rounding mode explanation

### ISSUE THREAD

**Issue by Merlin04** [Twixes/matloka.com#7]
On https://matloka.com/blog/floating-point-101#the-more-or-less, the first two rounding modes are described as:
> roundTowardPositive – takes the floor (i.e. towards positive infinity),
> roundTowardNegative – takes the ceiling (i.e. towards negative infinity),

Shouldn't floor and ceiling be swapped, since ceiling rounds up and floor rounds down? (I could very well be wrong on this, if so just let me know)

**Comment by Twixes** [comment]
That's a good catch, thanks! You're right, I must have reversed those points at some point and missed that the descriptions got out of sync. Fixed that in #8.

**Comment by Merlin04** [comment]
Awesome, thanks so much! Your article was super helpful for studying for CS class, if you ever want to expand on this in the future I think an explanation of math with floats (addition, multiplication, etc) in your style would be a very good read.
